/*
 * DotAAS Part 2 | HTTP/REST | Submodel Service Specification
 *
 * The Submodel Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) 2023
 *
 * OpenAPI spec version: V3.0.1_SSP-001
 * Contact: info@idtwin.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace AdminShellNS.Models
{
    public enum ExecutionState 
    {
        Initiated,
        Running,
        Completed,
        Canceled,
        Failed,
        Timeout
    }

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OperationResult
    {
        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>

        [MaxLength(128)]
        [DataMember(Name = "requestId")]
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or Sets OutputArguments
        /// </summary>
        
        [DataMember(Name = "outputArguments")]
        public List<OperationVariable> OutputArguments { get; set; }

        /// <summary>
        /// Gets or Sets InoutputArguments
        /// </summary>
        
        [DataMember(Name = "inoutputArguments")]
        public List<OperationVariable> InoutputArguments { get; set; }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        
        [DataMember(Name = "success")]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        
        [MaxLength(1024)]
        [DataMember(Name = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets ExecutionState
        /// </summary>

        [DataMember(Name = "executionState")]
        public ExecutionState ExecutionState { get; set; }

    }
}
