/*
 * DotAAS Part 2 | HTTP/REST | Submodel Service Specification
 *
 * The Submodel Service Specification as part of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub).   Publisher: Industrial Digital Twin Association (IDTA) 2023
 *
 * OpenAPI spec version: V3.0.1_SSP-001
 * Contact: info@idtwin.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace AdminShellNS.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OperationHandle
    {
        /// <summary>
        /// Gets or Sets RequestId
        /// </summary>

        [MaxLength(128)]
        [DataMember(Name = "requestId")]
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or Sets HandleId
        /// </summary>

        [MaxLength(128)]
        [DataMember(Name = "handleId")]
        public string HandleId { get; set; }

        /// <summary>
        /// Internal counter for handle Ids
        /// </summary>
        private static long _counter = 0;

        /// <summary>
        /// Creates a new handle with unique Id
        /// </summary>
        public static OperationHandle Create(string requestId) 
        {
            return new OperationHandle() {
                RequestId = requestId,
                HandleId = "" + _counter++
            };
        }

    }
}
